# Uncomment the following line to use OpenMP 2.0 features
#OMPFLAG = -DOMPVER2
# Uncomment the following line to use OpenMP 3.0 features
OMPFLAG = -DOMPVER2 -DOMPVER3

CC=gcc
CFLAGS =  -O1 -lm -I../build/ -fopenmp
LDFLAGS = -O0 -lm
CPP = /usr/bin/cpp
LIBS = -Wl,-rpath=../../build/.libs/ -L../../build/.libs/ -lgomp
