# Uncomment the following line to use OpenMP 2.0 features
#OMPFLAG = -DOMPVER2
# Uncomment the following line to use OpenMP 3.0 features
OMPFLAG = -DOMPVER2 -DOMPVER3

CC=gcc 
CFLAGS =  -O2 -lm -fopenmp -std=c99
LDFLAGS = -O2 -lm
CPP = /usr/bin/cpp
LIBS = -L ../../libgomp/libgomp/build/.libs -lpthread -lgomp
