#
# Copyright(C) 2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
#
# Builds CAP Benchmark suite for MPPA-256 architecture.
#

# Directories.
export LIBSRCDIR = $(CURDIR)/libsrc
export INCDIR = $(CURDIR)/include
export SRCDIR = $(CURDIR)/src
export K1_TOOLCHAIN_DIR = /usr/local/k1tools

# Builds all kernels.
all:
	cd $(SRCDIR) && $(MAKE) all
	
# Cleans compilation files.
clean:
	cd $(SRCDIR) && $(MAKE) clean
